#ifndef DEFINEEFFECTS_H
#define DEFINEEFFECTS_H

#define END                                             -1
#define FX_MODE_FILL                                            1
#define FX_MODE_BLINK                                           2
#define FX_MODE_RAINBOW_STATIC                                  3
#define FX_MODE_FILL_GRADIENT_TWO_COLORS                        4
#define FX_MODE_FILL_GRADIENT_THREE_COLORS                      5
#define FX_MODE_BACK_AND_FORTH_NO_SMOOTH_ONE_DOT                6
#define FX_MODE_BACK_AND_FORTH_NO_SMOOTH_LENGHTED_DOT           7
#define FX_MODE_HUE_FADING                                      8
#define FX_MODE_HUE_WHITE_WAVE                                  9
#define FX_MODE_DISPLAY_PALETTE_LINEAR                         10
#define FX_MODE_MOVING_PALETTE_LINEAR                          11
#define FX_MODE_SPOTLIGHTING_PALETTE                           12
#define FX_MODE_SIN_BEAT_8                                     13
#define FX_MODE_SIN_BEAT_8_PHASE_OFF                           14
#define FX_MODE_SIN_BEAT_8_TIME_OFF                            15
#define FX_MODE_TWO_SIN_BEAT_8                                 16
#define FX_MODE_THREE_SIN_BEAT_8                               17
#define FX_MODE_BRIGHTNESS_SIN_BEAT_PALETTE                    18
#define FX_MODE_FUNKY_RAINBOW_SIN_BEAT_8                       19
#define FX_MODE_FUNKY_RANGES_SIN_BEAT_8                        20
#define FX_MODE_FUNKY_RAINBOW_SIN_BEAT_8_TWO                   21
#define FX_MODE_FUNKY_RANGE_SIN_BEAT_8_TWO                     22
#define FX_MODE_MOVING_FUNKY_PALETTE                           23
#define FX_MODE_RAINBOW_WAVE                                   24
#define FX_MODE_CHOOSEN_WAVE                                   25
#define FX_MODE_FIRST_NOISE_RAINBOW                            26
#define FX_MODE_FIRST_NOISE_COLORS                             27
#define FX_MODE_NOISE_PALETTE                                  28
#define FX_MODE_RUN_FIRE                                       29
#define FX_MODE_SECOND_NOISE                                   30
#define FX_MODE_FILL_NOISE_16                                  31
#define FX_MODE_RAINBOW_DAVE                                   32
#define FX_MODE_MARQUEE_DAVE                                   33
#define FX_MODE_TWINKLE_OLD                                    34
#define FX_MODE_TWINKLE                                        35
#define FX_MODE_COMET                                          36
#define FX_MODE_COMET_ONCE                                     37
#define FX_MODE_BOUNCE                                         38
#define FX_MODE_FIRE                                           39
#define FX_MODE_STORM                                          40
#define FX_MODE_STORM_COLORED                                  41
#define FX_MODE_STORM_PALETTE                                  42
#define FX_MODE_LIGHTING                                       43
#define FX_MODE_LIGHTING_COLORED                               44
#define FX_MODE_LIGHTING_PALETTE                               45
#define FX_MODE_BEAT_8_TAIL                                    46
#define FX_MODE_BLEND_INTO_RAINBOW                             47
#define FX_MODE_BREATHE_V2                                     48
#define FX_MODE_CHASE_TARGET_TALES_VAR_A                       49
#define FX_MODE_CHASE_TARGET_TALES_VAR_B                       50
#define FX_MODE_CHASE_TARGET_TALES_VAR_C                       51
#define FX_MODE_EVERY_N_TIMER_VARIABLES                        52
#define FX_MODE_FILL_UP_STRING                                 53
#define FX_MODE_HEART_BEAT_2                                   54
#define FX_MODE_HEART_BEAT_3                                   55
#define FX_MODE_HEART_PULSE_BLOOD_FLOWING                      56
#define FX_MODE_LIGHT_HOUSE_BEACON_V2                          57
#define FX_MODE_MATCHING_GLITTER_1                             58
#define FX_MODE_MATCHING_GLITTER_2                             59
#define FX_MODE_MATCHING_GLITTER_3                             60
#define FX_MODE_MATCHING_GLITTER_4                             61
#define FX_MODE_MIRROR_FADE_ENDS                               62
#define FX_MODE_FIRE_2012                                      63
#define FX_MODE_FIRE_2012_HALF_STRIPE                          64
#define FX_MODE_MOVING_COLORED_BAR                             65
#define FX_MODE_REPEATING_PATTERNS                             66
#define FX_MODE_SAVED_PIXELS                                   67
#define FX_MODE_SIN_COS_LINEAR                                 68
#define FX_MODE_SPARKLES                                       69


#endif