#ifndef DEFINEEFFECTSETTINGS_H
#define DEFINEEFFECTSETTINGS_H

static int effect = 1;
static int speed = 100;


static CRGB             color2 = CRGB::Red;
static CRGB             color3 = CRGB::Red;
static CRGBPalette16    palette;
static uint8_t          bpm_sinBeat8 = 30;
static uint8_t          bpm_sinBeat8PhaseOff = 30;
static uint8_t          phaseOffset_sinBeat8PhaseOff = 30;
static uint8_t          bpm_sinBeat8TimeOff = 30;
static uint8_t          hueInsert_hueWhiteWave;
static uint8_t          bpm_twoSinBeat8;
static uint8_t          bpm_threeSinBeat8;
static uint8_t          bpm_brightnessSinBeat8Palette;
static uint8_t          bpm1_movingFunkyPalette;
static uint8_t          bpm2_movingFunkyPalette;
static uint8_t          bpm_rainbowWave;
static uint8_t          bpm_firstNoiseRainbow;
static uint8_t          bpm_beat8_tail;
static uint8_t          dub_offset_heartBeat2;
static uint8_t          frameDelay_movingColoredBar;

static uint16_t         timerA_everyNTimerVariables;
static uint16_t         timerB_everyNTimerVariables;
static uint16_t         beat_speed_heartBeat2;

static byte fade_bounce;

static int              r;
static int              g;
static int              b;
static int              tid_blink = 100;
static int              r2;
static int              g2;
static int              b2;
static int              r3;
static int              g3;
static int              b3;
static int              tid_backAndForthNoSmoothOneDot = 30;
static int              tid_backAndForthNoSmoothLengthedDot = 30;
static int              length_backAndForthNoSmoothLengthedDot = 3;
static int              tid_hueFading;
static int              tid_hueWhiteWave;
static int              tid_movingPaletteLinear;
static int              tid_spotlightingPalette;
static int              fade_spotlightingPalette;
static int              fade_sinBeat8;
static int              fade_sinBeat8PhaseOff;
static int              fade_sinBeat8TimeOff;
static int              time_sinBeat8TimeOff;
static int              fade_twoSinBeat8;
static int              fade_threeSinBeat8;
static int              tid_brightnessSinBeat8Palette;
static int              fade_funkyRainbowSinBeat8;
static int              fade_funkyRangeSinBeat8;
static int              fade_funkyRainbowSinBeat8Two;
static int              fade_funkyRangeSinBeat8Two;
static int              tid_rainbowWave;
static int              fade_rainbowWave;
static int              tid_choosenWave;
static int              fade_choosenWave;
static int              scale_noisePalette;
static int              density_rainbowDave;
static int              delta_rainbowDave;
static int              tid_rainbowDave;
static int              tid_marqueeDave;
static int              density_marqueeDave;
static int              length_marqueeDave;
static int              tid_twinkleOld;
static int              tid_twinkle;
static int              tid_comet;
static int              fade_comet;
static int              length_comet;
static int              density_comet;
static int              tid_cometOnce;
static int              fade_cometOnce;
static int              length_cometOnce;
static int              density_cometOnce;
static int              balls_bounce;
static int              size_fire;
static int              cooling_fire;
static int              sparking_fire;
static int              sparks_fire;
static int              sparkHeight_fire;
static int              chance_storm;
static int              length_storm;
static int              tid_storm;
static int              fade_storm;
static int              chance_stormColored;
static int              length_stormColored;
static int              tid_stormColored;
static int              fade_stormColored;
static int              chance_stormPalette;
static int              length_stormPalette;
static int              tid_stormPalette;
static int              fade_stormPalette;
static int              ledstart_lighting;
static int              length_lighting;
static int              flashes_lighting;
static int              dimmer_lighting;
static int              frequency_lighting;
static int              ledstart_lightingColored;
static int              length_lightingColored;
static int              flashes_lightingColored;
static int              dimmer_lightingColored;
static int              frequency_lightingColored;
static int              ledstart_lightingPalette;
static int              length_lightingPalette;
static int              flashes_lightingPalette;
static int              dimmer_lightingPalette;
static int              frequency_lightingPalette;
static int              fade_beat8_tail;
static int              tid_blendIntoRainbow;
static int              tid2_blendIntoRainbow;
static int              tid_chaseTargetTalesVarA;
static int              tid_chaseTargetTalesVarB;
static int              boilingTime_chaseTargetTalesVarC;
static int              tid_chaseTargetTalesVarC;
static int              fadeTime_chaseTargetTalesVarC;
static int              length_lighthouseBeaconV2;
static int              tid_lighthouseBeaconV2;
static int              fade_lighthouseBeaconV2;
static int              fade_mirrorFadeEnds;
static int              tid_Fire2012;
static int              cooling_Fire2012;
static int              sparking_Fire2012;
static int              tid_Fire2012_halfStrip;
static int              cooling_Fire2012_halfStrip;
static int              sparking_Fire2012_halfStrip;
static int              length_movingColoredBar;
static int              tid_repeatingPattern;
static int              tid2_repeatingPattern;
static int              fade_repeatingPattern;
static int              tid_savedPixel;
static int              tid2_savedPixel;
static int              sparkel_duration_sparkles;
static int              sparkel_amount_sparkles;
static int              sparkel_spread_sparkles;

static double           speed_cometOnce;

static float            pulseSp_breatheV2;

static bool             mirror_bounce;
static bool             breversed_fire;
static bool             bmirrored_fire;
static bool             gReverseDirection_Fire2012_halfStrip;
static bool             second_matchingGlitter3;
static bool             third_matchingGlitter3;
static bool             more_matchingGlitter4;
static bool             rainbow_heartBeat3;

#endif