#ifndef DEFINEEFFECTS_H
#define DEFINEEFFECTS_H

#define END                                             -1
#define FILL                                            1
#define BLINK                                           2
#define RAINBOW_STATIC                                  3
#define FILL_GRADIENT_TWO_COLORS                        4
#define FILL_GRADIENT_THREE_COLORS                      5
#define BACK_AND_FORTH_NO_SMOOTH_ONE_DOT                6
#define BACK_AND_FORTH_NO_SMOOTH_LENGHTED_DOT           7
#define HUE_FADING                                      8
#define HUE_WHITE_WAVE                                  9
#define DISPLAY_PALETTE_LINEAR                         10
#define MOVING_PALETTE_LINEAR                          11
#define SPOTLIGHTING_PALETTE                           12
#define SIN_BEAT_8                                     13
#define SIN_BEAT_8_PHASE_OFF                           14
#define SIN_BEAT_8_TIME_OFF                            15
#define TWO_SIN_BEAT_8                                 16
#define THREE_SIN_BEAT_8                               17
#define BRIGHTNESS_SIN_BEAT_PALETTE                    18
#define FUNKY_RAINBOW_SIN_BEAT_8                       19
#define FUNKY_RANGES_SIN_BEAT_8                        20
#define FUNKY_RAINBOW_SIN_BEAT_8_TWO                   21
#define FUNKY_RANGE_SIN_BEAT_8_TWO                     22
#define MOVING_FUNKY_PALETTE                           23
#define RAINBOW_WAVE                                   24
#define CHOOSEN_WAVE                                   25
#define FIRST_NOISE_RAINBOW                            26
#define FIRST_NOISE_COLORS                             27
#define NOISE_PALETTE                                  28
#define RUN_FIRE                                       29
#define SECOND_NOISE                                   30
#define FILL_NOISE_16                                  31
#define RAINBOW_DAVE                                   32
#define MARQUEE_DAVE                                   33
#define TWINKLE_OLD                                    34
#define TWINKLE                                        35
#define COMET                                          36
#define COMET_ONCE                                     37
#define BOUNCE                                         38
#define FIRE                                           39
#define STORM                                          40
#define STORM_COLORED                                  41
#define STORM_PALETTE                                  42
#define LIGHTING                                       43
#define LIGHTING_COLORED                               44
#define LIGHTING_PALETTE                               45
#define BEAT_8_TAIL                                    46
#define BLEND_INTO_RAINBOW                             47
#define BREATHE_V2                                     48
#define CHASE_TARGET_TALES_VAR_A                       49
#define CHASE_TARGET_TALES_VAR_B                       50
#define CHASE_TARGET_TALES_VAR_C                       51
#define EVERY_N_TIMER_VARIABLES                        52
#define FILL_UP_STRING                                 53
#define HEART_BEAT_2                                   54
#define HEART_BEAT_3                                   55
#define HEART_PULSE_BLOOD_FLOWING                      56
#define LIGHT_HOUSE_BEACON_V2                          57
#define MATCHING_GLITTER_1                             58
#define MATCHING_GLITTER_2                             59
#define MATCHING_GLITTER_3                             60
#define MATCHING_GLITTER_4                             61
#define MIRROR_FADE_ENDS                               62
#define FIRE_2012                                      63
#define FIRE_2012_HALF_STRIPE                          64
#define MOVING_COLORED_BAR                             65
#define REPEATING_PATTERNS                             66
#define SAVED_PIXELS                                   67
#define SIN_COS_LINEAR                                 68
#define SPARKLES                                       69


#endif